/**
 * Photoshop DOM enum values as synchronous, transport-safe runtime objects.
 *
 * Generated by `scripts/generate-photoshop-constants.mjs` from
 * `src/shared/types/photoshop/internal/dom/Constants.d.ts`. Do not edit by hand.
 */

/** Runtime values for Adobe Photoshop's `InterpolationMethod` enum. */
export const InterpolationMethod = {
  AUTOMATIC: "bicubicAutomatic",
  BICUBIC: "bicubic",
  BICUBICSHARPER: "bicubicSharper",
  BICUBICSMOOTHER: "bicubicSmoother",
  BILINEAR: "bilinear",
  NEARESTNEIGHBOR: "nearestNeighbor"
} as const;
export type InterpolationMethodValue = (typeof InterpolationMethod)[keyof typeof InterpolationMethod];

/** Runtime values for Adobe Photoshop's `ResampleMethod` enum. */
export const ResampleMethod = {
  AUTOMATIC: "bicubicAutomatic",
  BICUBIC: "bicubic",
  BICUBICSHARPER: "bicubicSharper",
  BICUBICSMOOTHER: "bicubicSmoother",
  BILINEAR: "bilinear",
  NEARESTNEIGHBOR: "nearestNeighbor",
  PRESERVEDETAILS: "preserveDetailsUpscale",
  DEEPUPSCALE: "deepUpscale",
  NONE: "none"
} as const;
export type ResampleMethodValue = (typeof ResampleMethod)[keyof typeof ResampleMethod];

/** Runtime values for Adobe Photoshop's `SaveMethod` enum. */
export const SaveMethod = {
  SAVE: "save",
  SAVEAS: "saveAs",
  SAVEASCOPY: "saveAsCopy"
} as const;
export type SaveMethodValue = (typeof SaveMethod)[keyof typeof SaveMethod];

/** Runtime values for Adobe Photoshop's `SaveOptions` enum. */
export const SaveOptions = {
  DONOTSAVECHANGES: 0,
  PROMPTTOSAVECHANGES: 1,
  SAVECHANGES: 2
} as const;
export type SaveOptionsValue = (typeof SaveOptions)[keyof typeof SaveOptions];

/** Runtime values for Adobe Photoshop's `BMPDepthType` enum. */
export const BMPDepthType = {
  ONE: "bitDepth1",
  FOUR: "bitDepth4",
  EIGHT: "bitDepth8",
  SIXTEEN: "bitDepth16",
  TWENTYFOUR: "bitDepth24",
  THIRTYTWO: "bitDepth32"
} as const;
export type BMPDepthTypeValue = (typeof BMPDepthType)[keyof typeof BMPDepthType];

/** Runtime values for Adobe Photoshop's `BitsPerChannelType` enum. */
export const BitsPerChannelType = {
  ONE: "bitDepth1",
  EIGHT: "bitDepth8",
  SIXTEEN: "bitDepth16",
  THIRTYTWO: "bitDepth32"
} as const;
export type BitsPerChannelTypeValue = (typeof BitsPerChannelType)[keyof typeof BitsPerChannelType];

/** Runtime values for Adobe Photoshop's `DepthMapSource` enum. */
export const DepthMapSource = {
  IMAGEHIGHLIGHT: "imageHighlight",
  LAYERMASK: "layerMask",
  NONE: "none",
  TRANSPARENCYCHANNEL: "transparency"
} as const;
export type DepthMapSourceValue = (typeof DepthMapSource)[keyof typeof DepthMapSource];

/** Runtime values for Adobe Photoshop's `OperatingSystem` enum. */
export const OperatingSystem = {
  WINDOWS: "windows",
  OS2: "OS2"
} as const;
export type OperatingSystemValue = (typeof OperatingSystem)[keyof typeof OperatingSystem];

/** Runtime values for Adobe Photoshop's `JPEGFormatOptions` enum. */
export const JPEGFormatOptions = {
  STANDARDBASELINE: "standardbaseline",
  PROGRESSIVE: "progressive",
  OPTIMIZEDBASELINE: "optimizedbaseline"
} as const;
export type JPEGFormatOptionsValue = (typeof JPEGFormatOptions)[keyof typeof JPEGFormatOptions];

/** Runtime values for Adobe Photoshop's `MatteColor` enum. */
export const MatteColor = {
  BACKGROUND: "backgroundColor",
  BLACK: "black",
  FOREGROUND: "foregroundColor",
  NETSCAPE: "netscapeGray",
  SEMIGRAY: "gray50",
  WHITE: "white"
} as const;
export type MatteColorValue = (typeof MatteColor)[keyof typeof MatteColor];

/** Runtime values for Adobe Photoshop's `Dither` enum. */
export const Dither = {
  DIFFUSION: "diffusion",
  PATTERN: "pattern",
  NOISE: "blue",
  NONE: "none"
} as const;
export type DitherValue = (typeof Dither)[keyof typeof Dither];

/** Runtime values for Adobe Photoshop's `ForcedColors` enum. */
export const ForcedColors = {
  NONE: "none",
  BLACKANDWHITE: "blackAndWhite",
  PRIMARIES: "primaries",
  WEB: "web"
} as const;
export type ForcedColorsValue = (typeof ForcedColors)[keyof typeof ForcedColors];

/** Runtime values for Adobe Photoshop's `Palette` enum. */
export const Palette = {
  EXACT: "exact",
  MACOSPALETTE: "macintoshSystem",
  WINDOWSPALETTE: "windowsSystem",
  WEBPALETTE: "web",
  UNIFORM: "uniform",
  LOCALPERCEPTUAL: "perceptual",
  LOCALSELECTIVE: "selective",
  LOCALADAPTIVE: "adaptive",
  MASTERPERCEPTUAL: "masterPerceptual",
  MASTERSELECTIVE: "masterSelective",
  MASTERADAPTIVE: "masterAdaptive",
  PREVIOUSPALETTE: "previous"
} as const;
export type PaletteValue = (typeof Palette)[keyof typeof Palette];

/** Runtime values for Adobe Photoshop's `PNGMethod` enum. */
export const PNGMethod = {
  QUICK: "quick",
  MODERATE: "moderate",
  THOROUGH: "thorough"
} as const;
export type PNGMethodValue = (typeof PNGMethod)[keyof typeof PNGMethod];

/** Runtime values for Adobe Photoshop's `AnchorPosition` enum. */
export const AnchorPosition = {
  BOTTOMCENTER: "bottom-center",
  BOTTOMLEFT: "bottom-left",
  BOTTOMRIGHT: "bottom-right",
  MIDDLECENTER: "middle-center",
  MIDDLELEFT: "middle-left",
  MIDDLERIGHT: "middle-right",
  TOPCENTER: "top-center",
  TOPLEFT: "top-left",
  TOPRIGHT: "top-right"
} as const;
export type AnchorPositionValue = (typeof AnchorPosition)[keyof typeof AnchorPosition];

/** Runtime values for Adobe Photoshop's `TrimType` enum. */
export const TrimType = {
  BOTTOMRIGHT: "bottom-right",
  TOPLEFT: "top-left",
  TRANSPARENT: "transparent"
} as const;
export type TrimTypeValue = (typeof TrimType)[keyof typeof TrimType];

/** Runtime values for Adobe Photoshop's `LabelColors` enum. */
export const LabelColors = {
  RED: "red",
  ORANGE: "orange",
  YELLOW: "yellowColor",
  GREEN: "grain",
  BLUE: "blue",
  VIOLET: "violet",
  GRAY: "gray",
  NONE: "none"
} as const;
export type LabelColorsValue = (typeof LabelColors)[keyof typeof LabelColors];

/** Runtime values for Adobe Photoshop's `BlendMode` enum. */
export const BlendMode = {
  NORMAL: "normal",
  DISSOLVE: "dissolve",
  DARKEN: "darken",
  MULTIPLY: "multiply",
  COLORBURN: "colorBurn",
  LINEARBURN: "linearBurn",
  DARKERCOLOR: "darkerColor",
  LIGHTEN: "lighten",
  SCREEN: "screen",
  COLORDODGE: "colorDodge",
  LINEARDODGE: "linearDodge",
  LIGHTERCOLOR: "lighterColor",
  OVERLAY: "overlay",
  SOFTLIGHT: "softLight",
  HARDLIGHT: "hardLight",
  VIVIDLIGHT: "vividLight",
  LINEARLIGHT: "linearLight",
  PINLIGHT: "pinLight",
  HARDMIX: "hardMix",
  DIFFERENCE: "difference",
  EXCLUSION: "exclusion",
  SUBTRACT: "blendSubtraction",
  DIVIDE: "blendDivide",
  HUE: "hue",
  SATURATION: "saturation",
  COLOR: "color",
  LUMINOSITY: "luminosity",
  PASSTHROUGH: "passThrough"
} as const;
export type BlendModeValue = (typeof BlendMode)[keyof typeof BlendMode];

/** Runtime values for Adobe Photoshop's `ColorBlendMode` enum. */
export const ColorBlendMode = {
  BEHIND: "behind",
  CLEAR: "clearEnum",
  COLOR: "color",
  COLORBURN: "colorBurn",
  COLORDODGE: "colorDodge",
  DARKEN: "darken",
  DARKERCOLOR: "darkerColor",
  DIFFERENCE: "difference",
  DISSOLVE: "dissolve",
  EXCLUSION: "exclusion",
  HARDLIGHT: "hardLight",
  HARDMIXBLEND: "hardMix",
  HUE: "hue",
  LIGHTEN: "lighten",
  LIGHTERCOLOR: "lighterColor",
  LINEARBURN: "linearBurn",
  LINEARDODGE: "linearDodge",
  LINEARLIGHT: "linearLight",
  LUMINOSITY: "luminosity",
  MULTIPLY: "multiply",
  NORMAL: "normal",
  OVERLAY: "overlay",
  PINLIGHT: "pinLight",
  SATURATION: "saturation",
  SCREEN: "screen",
  SOFTLIGHT: "softLight",
  VIVIDLIGHT: "vividLight"
} as const;
export type ColorBlendModeValue = (typeof ColorBlendMode)[keyof typeof ColorBlendMode];

/** Runtime values for Adobe Photoshop's `CalculationsBlendMode` enum. */
export const CalculationsBlendMode = {
  NORMAL: "normal",
  DARKEN: "darken",
  MULTIPLY: "multiply",
  COLORBURN: "colorBurn",
  LINEARBURN: "linearBurn",
  DARKERCOLOR: "darkerColor",
  LIGHTEN: "lighten",
  SCREEN: "screen",
  COLORDODGE: "colorDodge",
  LINEARDODGE: "linearDodge",
  LIGHTERCOLOR: "lighterColor",
  OVERLAY: "overlay",
  SOFTLIGHT: "softLight",
  HARDLIGHT: "hardLight",
  VIVIDLIGHT: "vividLight",
  LINEARLIGHT: "linearLight",
  PINLIGHT: "pinLight",
  HARDMIX: "hardMix",
  ADD: "add",
  SUBTRACT: "subtract",
  DIFFERENCE: "difference",
  EXCLUSION: "exclusion",
  DIVIDE: "blendDivide"
} as const;
export type CalculationsBlendModeValue = (typeof CalculationsBlendMode)[keyof typeof CalculationsBlendMode];

/** Runtime values for Adobe Photoshop's `ApplyImageBlendMode` enum. */
export const ApplyImageBlendMode = {
  NORMAL: "normal",
  DARKEN: "darken",
  MULTIPLY: "multiply",
  COLORBURN: "colorBurn",
  LINEARBURN: "linearBurn",
  DARKERCOLOR: "darkerColor",
  LIGHTEN: "lighten",
  SCREEN: "screen",
  COLORDODGE: "colorDodge",
  LINEARDODGE: "linearDodge",
  LIGHTERCOLOR: "lighterColor",
  OVERLAY: "overlay",
  SOFTLIGHT: "softLight",
  HARDLIGHT: "hardLight",
  VIVIDLIGHT: "vividLight",
  LINEARLIGHT: "linearLight",
  PINLIGHT: "pinLight",
  HARDMIX: "hardMix",
  ADD: "add",
  SUBTRACT: "subtract",
  DIFFERENCE: "difference",
  EXCLUSION: "exclusion",
  DIVIDE: "blendDivide"
} as const;
export type ApplyImageBlendModeValue = (typeof ApplyImageBlendMode)[keyof typeof ApplyImageBlendMode];

/** Runtime values for Adobe Photoshop's `DocumentMode` enum. */
export const DocumentMode = {
  BITMAP: "bitmapMode",
  CMYK: "CMYKColorMode",
  DUOTONE: "duotoneMode",
  GRAYSCALE: "grayscaleMode",
  INDEXEDCOLOR: "indexedColorMode",
  LAB: "labColorMode",
  MULTICHANNEL: "multichannelMode",
  RGB: "RGBColorMode"
} as const;
export type DocumentModeValue = (typeof DocumentMode)[keyof typeof DocumentMode];

/** Runtime values for Adobe Photoshop's `NewDocumentMode` enum. */
export const NewDocumentMode = {
  BITMAP: "bitmapMode",
  GRAYSCALE: "grayscaleMode",
  RGB: "RGBColorMode",
  CMYK: "CMYKColorMode",
  LAB: "labColorMode"
} as const;
export type NewDocumentModeValue = (typeof NewDocumentMode)[keyof typeof NewDocumentMode];

/** Runtime values for Adobe Photoshop's `Units` enum. */
export const Units = {
  CM: "cm",
  INCHES: "in",
  MM: "mm",
  PICAS: "pc",
  PIXELS: "px",
  POINTS: "pt"
} as const;
export type UnitsValue = (typeof Units)[keyof typeof Units];

/** Runtime values for Adobe Photoshop's `ChangeMode` enum. */
export const ChangeMode = {
  BITMAP: "bitmapMode",
  CMYK: "CMYKColorMode",
  GRAYSCALE: "grayscaleMode",
  INDEXEDCOLOR: "indexedColorMode",
  LAB: "labColorMode",
  MULTICHANNEL: "multichannelMode",
  RGB: "RGBColorMode"
} as const;
export type ChangeModeValue = (typeof ChangeMode)[keyof typeof ChangeMode];

/** Runtime values for Adobe Photoshop's `DocumentFill` enum. */
export const DocumentFill = {
  WHITE: "white",
  BLACK: "black",
  BACKGROUNDCOLOR: "backgroundColor",
  TRANSPARENT: "transparent",
  COLOR: "color"
} as const;
export type DocumentFillValue = (typeof DocumentFill)[keyof typeof DocumentFill];

/** Runtime values for Adobe Photoshop's `LayerKind` enum. */
export const LayerKind = {
  BLACKANDWHITE: "blackAndWhite",
  BRIGHTNESSCONTRAST: "brightnessContrast",
  CHANNELMIXER: "channelMixer",
  COLORBALANCE: "colorBalance",
  CURVES: "curves",
  EXPOSURE: "exposure",
  GRADIENTFILL: "gradientFill",
  GRADIENTMAP: "gradientMap",
  HUESATURATION: "hueSaturation",
  INVERSION: "inversion",
  LEVELS: "levels",
  NORMAL: "pixel",
  PATTERNFILL: "pattern",
  PHOTOFILTER: "photoFilter",
  POSTERIZE: "posterize",
  SELECTIVECOLOR: "selectiveColor",
  SMARTOBJECT: "smartObject",
  SOLIDFILL: "solidColor",
  TEXT: "text",
  THRESHOLD: "threshold",
  LAYER3D: "threeD",
  VIBRANCE: "vibrance",
  VIDEO: "video",
  GROUP: "group",
  COLORLOOKUP: "colorLookup",
  CLARITY: "clarity",
  GRAIN: "grain"
} as const;
export type LayerKindValue = (typeof LayerKind)[keyof typeof LayerKind];

/** Runtime values for Adobe Photoshop's `ElementPlacement` enum. */
export const ElementPlacement = {
  PLACEBEFORE: "placeBefore",
  PLACEATBEGINNING: "placeAtBeginning",
  PLACEATEND: "placeAtEnd",
  PLACEAFTER: "placeAfter",
  PLACEINSIDE: "placeInside"
} as const;
export type ElementPlacementValue = (typeof ElementPlacement)[keyof typeof ElementPlacement];

/** Runtime values for Adobe Photoshop's `ColorProfileType` enum. */
export const ColorProfileType = {
  CUSTOM: "customEnum",
  NONE: "none",
  WORKING: "workingSpaceCode"
} as const;
export type ColorProfileTypeValue = (typeof ColorProfileType)[keyof typeof ColorProfileType];

/** Runtime values for Adobe Photoshop's `BitmapConversionType` enum. */
export const BitmapConversionType = {
  CUSTOMPATTERN: "customPattern",
  DIFFUSIONDITHER: "diffusionDither",
  HALFTHRESHOLD: "halfThreshold",
  HALFTONESCREEN: "halfToneScreen",
  PATTERNDITHER: "patternDither"
} as const;
export type BitmapConversionTypeValue = (typeof BitmapConversionType)[keyof typeof BitmapConversionType];

/** Runtime values for Adobe Photoshop's `BitmapHalfToneType` enum. */
export const BitmapHalfToneType = {
  CROSS: "cross",
  DIAMOND: "diamond",
  ELLIPSE: "ellipse",
  LINE: "lineClass",
  ROUND: "round",
  SQUARE: "square"
} as const;
export type BitmapHalfToneTypeValue = (typeof BitmapHalfToneType)[keyof typeof BitmapHalfToneType];

/** Runtime values for Adobe Photoshop's `Intent` enum. */
export const Intent = {
  ABSOLUTECOLORIMETRIC: "absColorimetric",
  PERCEPTUAL: "image",
  RELATIVECOLORIMETRIC: "colorimetric",
  SATURATION: "graphics"
} as const;
export type IntentValue = (typeof Intent)[keyof typeof Intent];

/** Runtime values for Adobe Photoshop's `Direction` enum. */
export const Direction = {
  HORIZONTAL: "horizontal",
  VERTICAL: "vertical"
} as const;
export type DirectionValue = (typeof Direction)[keyof typeof Direction];

/** Runtime values for Adobe Photoshop's `Orientation` enum. */
export const Orientation = {
  HORIZONTAL: "horizontal",
  VERTICAL: "vertical"
} as const;
export type OrientationValue = (typeof Orientation)[keyof typeof Orientation];

/** Runtime values for Adobe Photoshop's `ColorModel` enum. */
export const ColorModel = {
  GRAYSCALE: "grayScale",
  HSB: "HSBColorEnum",
  CMYK: "CMYKColorEnum",
  LAB: "labColor",
  RGB: "RGBColor",
  NONE: "noColor"
} as const;
export type ColorModelValue = (typeof ColorModel)[keyof typeof ColorModel];

/** Runtime values for Adobe Photoshop's `RasterizeType` enum. */
export const RasterizeType = {
  ENTIRELAYER: "entire",
  FILLCONTENT: "content",
  LAYERCLIPPINGPATH: "clippingPath",
  LINKEDLAYERS: "linked",
  SHAPE: "shape",
  TEXTCONTENTS: "type",
  VECTORMASK: "vectorMask",
  PLACED: "placed",
  VIDEO: "video",
  LAYERSTYLE: "layerStyle"
} as const;
export type RasterizeTypeValue = (typeof RasterizeType)[keyof typeof RasterizeType];

/** Runtime values for Adobe Photoshop's `DialogModes` enum. */
export const DialogModes = {
  ALL: "display",
  ERROR: "silent",
  NONE: "dontDisplay"
} as const;
export type DialogModesValue = (typeof DialogModes)[keyof typeof DialogModes];

/** Runtime values for Adobe Photoshop's `DisplacementMapType` enum. */
export const DisplacementMapType = {
  STRETCHTOFIT: "stretchToFit",
  TILE: "tile"
} as const;
export type DisplacementMapTypeValue = (typeof DisplacementMapType)[keyof typeof DisplacementMapType];

/** Runtime values for Adobe Photoshop's `ChannelType` enum. */
export const ChannelType = {
  COMPONENT: "component",
  MASKEDAREA: "maskedAreas",
  SELECTEDAREA: "selectedAreas",
  SPOTCOLOR: "spot"
} as const;
export type ChannelTypeValue = (typeof ChannelType)[keyof typeof ChannelType];

/** Runtime values for Adobe Photoshop's `NoiseDistribution` enum. */
export const NoiseDistribution = {
  GAUSSIAN: "gaussianDistribution",
  UNIFORM: "uniformDistribution"
} as const;
export type NoiseDistributionValue = (typeof NoiseDistribution)[keyof typeof NoiseDistribution];

/** Runtime values for Adobe Photoshop's `EliminateFields` enum. */
export const EliminateFields = {
  EVENFIELDS: "eliminateEvenFields",
  ODDFIELDS: "eliminateOddFields"
} as const;
export type EliminateFieldsValue = (typeof EliminateFields)[keyof typeof EliminateFields];

/** Runtime values for Adobe Photoshop's `Geometry` enum. */
export const Geometry = {
  HEPTAGON: "heptagon",
  HEXAGON: "hexagon",
  OCTAGON: "octagon",
  PENTAGON: "pentagon",
  SQUARE: "square",
  TRIANGLE: "triangle"
} as const;
export type GeometryValue = (typeof Geometry)[keyof typeof Geometry];

/** Runtime values for Adobe Photoshop's `CreateFields` enum. */
export const CreateFields = {
  DUPLICATION: "createDroplet",
  INTERPOLATION: "createInterpolation"
} as const;
export type CreateFieldsValue = (typeof CreateFields)[keyof typeof CreateFields];

/** Runtime values for Adobe Photoshop's `PathKind` enum. */
export const PathKind = {
  DUPLICATE: "duplicate",
  INTERPOLATE: "interpolate",
  CLIPPINGPATH: "clippingPathEPS",
  NORMALPATH: "normalPath",
  TEXTMASK: "textShape",
  VECTORMASK: "vectorMask",
  WORKPATH: "workPathIndex"
} as const;
export type PathKindValue = (typeof PathKind)[keyof typeof PathKind];

/** Runtime values for Adobe Photoshop's `SelectionType` enum. */
export const SelectionType = {
  DIMINISH: "subtractFrom",
  EXTEND: "addTo",
  INTERSECT: "intersectWith",
  REPLACE: "set"
} as const;
export type SelectionTypeValue = (typeof SelectionType)[keyof typeof SelectionType];

/** Runtime values for Adobe Photoshop's `ToolType` enum. */
export const ToolType = {
  ARTHISTORYBRUSH: "artBrushTool",
  BACKGROUNDERASER: "backgroundEraserTool",
  BLUR: "blurTool",
  BRUSH: "paintbrushTool",
  BURN: "burnInTool",
  CLONESTAMP: "cloneStampTool",
  COLORREPLACEMENTTOOL: "colorReplacementBrushTool",
  DODGE: "dodgeTool",
  ERASER: "eraserTool",
  HEALINGBRUSH: "magicStampTool",
  HISTORYBRUSH: "historyBrushTool",
  PATTERNSTAMP: "patternStampTool",
  PENCIL: "pencilTool",
  SHARPEN: "sharpenTool",
  SMUDGE: "smudgeTool",
  SPONGE: "saturationTool"
} as const;
export type ToolTypeValue = (typeof ToolType)[keyof typeof ToolType];

/** Runtime values for Adobe Photoshop's `PointKind` enum. */
export const PointKind = {
  CORNERPOINT: "cornerPoint",
  SMOOTHPOINT: "smoothPoint"
} as const;
export type PointKindValue = (typeof PointKind)[keyof typeof PointKind];

/** Runtime values for Adobe Photoshop's `ShapeOperation` enum. */
export const ShapeOperation = {
  SHAPEADD: "add",
  SHAPEINTERSECT: "intersect",
  SHAPESUBTRACT: "subtract",
  SHAPEXOR: "xor"
} as const;
export type ShapeOperationValue = (typeof ShapeOperation)[keyof typeof ShapeOperation];

/** Runtime values for Adobe Photoshop's `TextureType` enum. */
export const TextureType = {
  BLOCKS: "texTypeBlocks",
  CANVAS: "texTypeCanvas",
  FROSTED: "texTypeFrosted",
  TINYLENS: "texTypeTinyLens"
} as const;
export type TextureTypeValue = (typeof TextureType)[keyof typeof TextureType];

/** Runtime values for Adobe Photoshop's `UndefinedAreas` enum. */
export const UndefinedAreas = {
  REPEATEDGEPIXELS: "repeatEdgePixels",
  WRAPAROUND: "wrapAround"
} as const;
export type UndefinedAreasValue = (typeof UndefinedAreas)[keyof typeof UndefinedAreas];

/** Runtime values for Adobe Photoshop's `PolarConversionType` enum. */
export const PolarConversionType = {
  POLARTORECTANGULAR: "polarToRect",
  RECTANGULARTOPOLAR: "rectToPolar"
} as const;
export type PolarConversionTypeValue = (typeof PolarConversionType)[keyof typeof PolarConversionType];

/** Runtime values for Adobe Photoshop's `RadialBlurMethod` enum. */
export const RadialBlurMethod = {
  SPIN: "spin",
  ZOOM: "zoom"
} as const;
export type RadialBlurMethodValue = (typeof RadialBlurMethod)[keyof typeof RadialBlurMethod];

/** Runtime values for Adobe Photoshop's `RadialBlurQuality` enum. */
export const RadialBlurQuality = {
  DRAFT: "draft",
  GOOD: "good",
  BEST: "best"
} as const;
export type RadialBlurQualityValue = (typeof RadialBlurQuality)[keyof typeof RadialBlurQuality];

/** Runtime values for Adobe Photoshop's `RippleSize` enum. */
export const RippleSize = {
  LARGE: "large",
  MEDIUM: "mediumQuality",
  SMALL: "small"
} as const;
export type RippleSizeValue = (typeof RippleSize)[keyof typeof RippleSize];

/** Runtime values for Adobe Photoshop's `SmartBlurQuality` enum. */
export const SmartBlurQuality = {
  HIGH: "smartBlurQualityHigh",
  LOW: "smartBlurQualityLow",
  MEDIUM: "smartBlurQualityMedium"
} as const;
export type SmartBlurQualityValue = (typeof SmartBlurQuality)[keyof typeof SmartBlurQuality];

/** Runtime values for Adobe Photoshop's `SmartBlurMode` enum. */
export const SmartBlurMode = {
  EDGEONLY: "smartBlurModeEdgeOnly",
  NORMAL: "smartBlurModeNormal",
  OVERLAYEDGE: "smartBlurModeOverlayEdge"
} as const;
export type SmartBlurModeValue = (typeof SmartBlurMode)[keyof typeof SmartBlurMode];

/** Runtime values for Adobe Photoshop's `SpherizeMode` enum. */
export const SpherizeMode = {
  HORIZONTAL: "horizontalOnly",
  NORMAL: "normal",
  VERTICAL: "verticalOnly"
} as const;
export type SpherizeModeValue = (typeof SpherizeMode)[keyof typeof SpherizeMode];

/** Runtime values for Adobe Photoshop's `WaveType` enum. */
export const WaveType = {
  SINE: "waveSine",
  SQUARE: "waveSquare",
  TRIANGULAR: "waveTriangle"
} as const;
export type WaveTypeValue = (typeof WaveType)[keyof typeof WaveType];

/** Runtime values for Adobe Photoshop's `ZigZagType` enum. */
export const ZigZagType = {
  AROUNDCENTER: "aroundCenter",
  OUTFROMCENTER: "outFromCenter",
  PONDRIPPLES: "pondRipples"
} as const;
export type ZigZagTypeValue = (typeof ZigZagType)[keyof typeof ZigZagType];

/** Runtime values for Adobe Photoshop's `LensType` enum. */
export const LensType = {
  MOVIEPRIME: "panaVision",
  PRIME105: "nikon105",
  PRIME35: "nikon",
  ZOOMLENS: "zoom"
} as const;
export type LensTypeValue = (typeof LensType)[keyof typeof LensType];

/** Runtime values for Adobe Photoshop's `PreserveShape` enum. */
export const PreserveShape = {
  SQUARENESS: "squareness",
  ROUNDNESS: "roundness"
} as const;
export type PreserveShapeValue = (typeof PreserveShape)[keyof typeof PreserveShape];

/** Runtime values for Adobe Photoshop's `OffsetUndefinedAreas` enum. */
export const OffsetUndefinedAreas = {
  SETTOBACKGROUND: "background",
  REPEATEDGEPIXELS: "repeat",
  WRAPAROUND: "wrap"
} as const;
export type OffsetUndefinedAreasValue = (typeof OffsetUndefinedAreas)[keyof typeof OffsetUndefinedAreas];

/** Runtime values for Adobe Photoshop's `SampleSize` enum. */
export const SampleSize = {
  POINTSAMPLE: 0,
  SAMPLE3X3: 1,
  SAMPLE5X5: 2,
  SAMPLE11X11: 5,
  SAMPLE31X31: 15,
  SAMPLE51X51: 25,
  SAMPLE101X101: 50
} as const;
export type SampleSizeValue = (typeof SampleSize)[keyof typeof SampleSize];

/** Runtime values for Adobe Photoshop's `SavePreview` enum. */
export const SavePreview = {
  ALWAYSSAVE: "queryAlways",
  ASKWHENSAVING: "queryAsk",
  NEVERSAVE: "queryNever"
} as const;
export type SavePreviewValue = (typeof SavePreview)[keyof typeof SavePreview];

/** Runtime values for Adobe Photoshop's `ColorPicker` enum. */
export const ColorPicker = {
  ADOBE: "photoshopPicker",
  OSNATIVE: "systemPicker",
  PLUGIN: "pluginPicker"
} as const;
export type ColorPickerValue = (typeof ColorPicker)[keyof typeof ColorPicker];

/** Runtime values for Adobe Photoshop's `EditLogItemsType` enum. */
export const EditLogItemsType = {
  CONCISE: "concise",
  DETAILED: "detailed",
  SESSIONONLY: "session"
} as const;
export type EditLogItemsTypeValue = (typeof EditLogItemsType)[keyof typeof EditLogItemsType];

/** Runtime values for Adobe Photoshop's `GridSize` enum. */
export const GridSize = {
  LARGE: "large",
  MEDIUM: "medium",
  NONE: "none",
  SMALL: "small"
} as const;
export type GridSizeValue = (typeof GridSize)[keyof typeof GridSize];

/** Runtime values for Adobe Photoshop's `GridLineStyle` enum. */
export const GridLineStyle = {
  DASHED: "dashedLines",
  DOTTED: "dots",
  SOLID: "lens"
} as const;
export type GridLineStyleValue = (typeof GridLineStyle)[keyof typeof GridLineStyle];

/** Runtime values for Adobe Photoshop's `GuideLineStyle` enum. */
export const GuideLineStyle = {
  DASHED: "dashedLines",
  SOLID: "lens"
} as const;
export type GuideLineStyleValue = (typeof GuideLineStyle)[keyof typeof GuideLineStyle];

/** Runtime values for Adobe Photoshop's `MaximizeCompatibility` enum. */
export const MaximizeCompatibility = {
  ALWAYS: "queryAlways",
  ASK: "queryAsk",
  NEVER: "queryNever"
} as const;
export type MaximizeCompatibilityValue = (typeof MaximizeCompatibility)[keyof typeof MaximizeCompatibility];

/** Runtime values for Adobe Photoshop's `OtherCursors` enum. */
export const OtherCursors = {
  PRECISE: "precise",
  STANDARD: "standard"
} as const;
export type OtherCursorsValue = (typeof OtherCursors)[keyof typeof OtherCursors];

/** Runtime values for Adobe Photoshop's `PaintingCursors` enum. */
export const PaintingCursors = {
  FULLSIZE: "fullSize",
  BRUSHSIZE: "brushSize",
  PRECISE: "precise",
  STANDARD: "standard"
} as const;
export type PaintingCursorsValue = (typeof PaintingCursors)[keyof typeof PaintingCursors];

/** Runtime values for Adobe Photoshop's `PointType` enum. */
export const PointType = {
  POSTSCRIPT: "POSTSCRIPT",
  TRADITIONAL: "TRADITIONAL"
} as const;
export type PointTypeValue = (typeof PointType)[keyof typeof PointType];

/** Runtime values for Adobe Photoshop's `SaveLogItemsType` enum. */
export const SaveLogItemsType = {
  LOGFILE: "textFile",
  LOGFILEANDMETADATA: "both",
  METADATA: "metadata"
} as const;
export type SaveLogItemsTypeValue = (typeof SaveLogItemsType)[keyof typeof SaveLogItemsType];

/** Runtime values for Adobe Photoshop's `FontSize` enum. */
export const FontSize = {
  TINY: "preferTinyPaletteFontType",
  LARGE: "preferLargePaletteFontType",
  MEDIUM: "preferMediumPaletteFontType",
  SMALL: "preferSmallPaletteFontType"
} as const;
export type FontSizeValue = (typeof FontSize)[keyof typeof FontSize];

/** Runtime values for Adobe Photoshop's `TypeUnits` enum. */
export const TypeUnits = {
  MILLIMETERS: "rulerMm",
  PIXELS: "rulerPixels",
  POINTS: "rulerPoints"
} as const;
export type TypeUnitsValue = (typeof TypeUnits)[keyof typeof TypeUnits];

/** Runtime values for Adobe Photoshop's `RulerUnits` enum. */
export const RulerUnits = {
  CENTIMETERS: "rulerCm",
  INCHES: "rulerInches",
  MILLIMETERS: "rulerMm",
  PERCENT: "rulerPercent",
  PICAS: "rulerPicas",
  PIXELS: "rulerPixels",
  POINTS: "rulerPoints"
} as const;
export type RulerUnitsValue = (typeof RulerUnits)[keyof typeof RulerUnits];

/** Runtime values for Adobe Photoshop's `TypeInterfaceFeatures` enum. */
export const TypeInterfaceFeatures = {
  DEFAULT: "defaultTextInterface",
  EASTASIAN: "advancedAsianInterface",
  MIDDLEEASTERN: "middleEasternInterface"
} as const;
export type TypeInterfaceFeaturesValue = (typeof TypeInterfaceFeatures)[keyof typeof TypeInterfaceFeatures];

/** Runtime values for Adobe Photoshop's `CalculationsResult` enum. */
export const CalculationsResult = {
  NEWDOCUMENT: "document",
  NEWCHANNEL: "channel",
  SELECTION: "selection"
} as const;
export type CalculationsResultValue = (typeof CalculationsResult)[keyof typeof CalculationsResult];

/** Runtime values for Adobe Photoshop's `CalculationsChannel` enum. */
export const CalculationsChannel = {
  TRANSPARENCY: "transparencyEnum",
  SELECTION: "selection",
  GRAY: "gray"
} as const;
export type CalculationsChannelValue = (typeof CalculationsChannel)[keyof typeof CalculationsChannel];

/** Runtime values for Adobe Photoshop's `ApplyImageChannel` enum. */
export const ApplyImageChannel = {
  TRANSPARENCY: "transparencyEnum",
  SELECTION: "selection",
  RGB: "RGB",
  CMYK: "CMYK",
  LAB: "lab"
} as const;
export type ApplyImageChannelValue = (typeof ApplyImageChannel)[keyof typeof ApplyImageChannel];

/** Runtime values for Adobe Photoshop's `CalculationsLayer` enum. */
export const CalculationsLayer = {
  MERGED: "merged"
} as const;
export type CalculationsLayerValue = (typeof CalculationsLayer)[keyof typeof CalculationsLayer];

/** Runtime values for Adobe Photoshop's `ApplyImageLayer` enum. */
export const ApplyImageLayer = {
  MERGED: "merged"
} as const;
export type ApplyImageLayerValue = (typeof ApplyImageLayer)[keyof typeof ApplyImageLayer];

/** Runtime values for Adobe Photoshop's `AntiAlias` enum. */
export const AntiAlias = {
  NONE: "antiAliasNone",
  SHARP: "antiAliasSharp",
  CRISP: "antiAliasCrisp",
  STRONG: "antiAliasStrong",
  SMOOTH: "antiAliasSmooth"
} as const;
export type AntiAliasValue = (typeof AntiAlias)[keyof typeof AntiAlias];

/** Runtime values for Adobe Photoshop's `WarpStyle` enum. */
export const WarpStyle = {
  ARC: "warpArc",
  ARCH: "warpArch",
  ARCLOWER: "warpArcLower",
  ARCUPPER: "warpArcUpper",
  BULGE: "warpBulge",
  FISH: "warpFish",
  FISHEYE: "warpFisheye",
  FLAG: "warpFlag",
  INFLATE: "warpInflate",
  NONE: "warpNone",
  RISE: "warpRise",
  SHELLLOWER: "warpShellLower",
  SHELLUPPER: "warpShellUpper",
  SQUEEZE: "warpSqueeze",
  TWIST: "warpTwist",
  WAVE: "warpWave"
} as const;
export type WarpStyleValue = (typeof WarpStyle)[keyof typeof WarpStyle];

/** Runtime values for Adobe Photoshop's `AutoKernType` enum. */
export const AutoKernType = {
  MANUAL: "manual",
  METRICS: "metricsKern",
  OPTICAL: "opticalKern"
} as const;
export type AutoKernTypeValue = (typeof AutoKernType)[keyof typeof AutoKernType];

/** Runtime values for Adobe Photoshop's `TextCase` enum. */
export const TextCase = {
  ALLCAPS: "allCaps",
  NORMAL: "normal",
  SMALLCAPS: "smallCaps"
} as const;
export type TextCaseValue = (typeof TextCase)[keyof typeof TextCase];

/** Runtime values for Adobe Photoshop's `Baseline` enum. */
export const Baseline = {
  NORMAL: "normal",
  SUPERSCRIPT: "superScript",
  SUBSCRIPT: "subScript"
} as const;
export type BaselineValue = (typeof Baseline)[keyof typeof Baseline];

/** Runtime values for Adobe Photoshop's `Underline` enum. */
export const Underline = {
  NONE: "underlineOff",
  RIGHTINVERTICAL: "underlineOnRightInVertical",
  LEFTINVERTICAL: "underlineOnLeftInVertical"
} as const;
export type UnderlineValue = (typeof Underline)[keyof typeof Underline];

/** Runtime values for Adobe Photoshop's `Language` enum. */
export const Language = {
  ENGLISHUSA: "englishLanguage",
  ENGLISHUK: "ukenglishLanguage",
  ENGLISHCANADA: "canadianEnglishLanguage",
  FINNISH: "finnishLanguage",
  FRENCH: "standardFrenchLanguage",
  CANADIANFRENCH: "canadianFrenchLanguage",
  GERMAN: "standardGermanLanguage",
  GERMAN1996: "germanLanguageReformed1996",
  OLDGERMAN: "oldGermanLanguage",
  SWISSGERMAN: "swissGermanLanguage",
  OLDSWISSGERMAN: "swissGermanLanguageOldRules",
  ITALIAN: "italianLanguage",
  NORWEGIAN: "bokmalNorwegianLanguage",
  NYNORSKNORWEGIAN: "nynorskNorwegianLanguage",
  PORTUGUESE: "standardPortugueseLanguage",
  BRAZILLIANPORTUGUESE: "brazilianPortugueseLanguage",
  SPANISH: "spanishLanguage",
  SWEDISH: "swedishLanguage",
  DUTCH: "dutchLanguage",
  OLDDUTCH: "kdutchLanguageOldRules",
  DANISH: "danishLanguage",
  RUSSIAN: "russianLanguage",
  SERBIAN: "serbianLanguage",
  CZECH: "czechLanguage",
  POLISH: "polishLanguage",
  GREEK: "greekLanguage",
  TURKISH: "turkishLanguage",
  ICELANDIC: "icelandicLanguage",
  HUNGARIAN: "hungarianLanguage",
  CATALAN: "catalanLanguage",
  CROATIAN: "croatianLanguage",
  ROMANIAN: "romanianLanguage",
  UKRAINIAN: "ukranianLanguage",
  SLOVENIAN: "slovenianLanguage",
  BULGARIAN: "bulgarianLanguage",
  LATVIAN: "latvianLanguage",
  LITHUANIAN: "lithuanianLanguage",
  ESTONIAN: "estonianLanguage",
  SLOVAK: "slovakLanguage",
  CHINESE: "chineseLanguage",
  JAPANESE: "japaneseLanguage",
  ARABIC: "arabicLanguage",
  HEBREW: "hebrewLanguage",
  HINDI: "hindiLanguage",
  BANGLAINDIA: "bengaliIndiaLanguage",
  TAMIL: "tamilLanguage",
  MALAYALAM: "malayalamLanguage",
  TELUGU: "teluguLanguage",
  KANNADA: "kannadaLanguage",
  GUJARATI: "gujaratiLanguage",
  MARATHI: "marathiLanguage",
  PUNJABI: "punjabiLanguage",
  ODIA: "oriyaLanguage",
  THAI: "thaiLanguage",
  KHMER: "khmerLanguage",
  BURMESE: "burmeseLanguage",
  LAO: "laoLanguage",
  SINHALESE: "sinhaleseLanguage",
  INDONESIAN: "indonesianLanguage"
} as const;
export type LanguageValue = (typeof Language)[keyof typeof Language];

/** Runtime values for Adobe Photoshop's `Justification` enum. */
export const Justification = {
  LEFT: "left",
  CENTER: "center",
  RIGHT: "right",
  LEFTJUSTIFIED: "justifyLeft",
  CENTERJUSTIFIED: "justifyCenter",
  RIGHTJUSTIFIED: "justifyRight",
  FULLYJUSTIFIED: "justifyAll"
} as const;
export type JustificationValue = (typeof Justification)[keyof typeof Justification];

/** Runtime values for Adobe Photoshop's `StrikeThrough` enum. */
export const StrikeThrough = {
  STRIKEBOX: "eMBoxStrikethroughOn",
  STRIKEHEIGHT: "xHeightStrikethroughOn",
  STRIKEOFF: "strikethroughOff"
} as const;
export type StrikeThroughValue = (typeof StrikeThrough)[keyof typeof StrikeThrough];

/** Runtime values for Adobe Photoshop's `CharacterAlignment` enum. */
export const CharacterAlignment = {
  ROMAN: "roman",
  EMBOXTOPRIGHT: "top",
  EMBOXCENTER: "center",
  EMBOXBOTTOMLEFT: "bottom",
  ICFBOXTOPRIGHT: "icftop",
  ICFBOTTOMLEFT: "icfbottom"
} as const;
export type CharacterAlignmentValue = (typeof CharacterAlignment)[keyof typeof CharacterAlignment];

/** Runtime values for Adobe Photoshop's `ParagraphLayout` enum. */
export const ParagraphLayout = {
  LATINEASTASIAN: "textLatinCJKComposer",
  WORLDREADY: "textOptycaComposer"
} as const;
export type ParagraphLayoutValue = (typeof ParagraphLayout)[keyof typeof ParagraphLayout];

/** Runtime values for Adobe Photoshop's `ParagraphFeatures` enum. */
export const ParagraphFeatures = {
  DEFAULT: "defaultTextInterface",
  EASTASIAN: "advancedAsianInterface",
  MIDDLEASTERN: "middleEasternInterface"
} as const;
export type ParagraphFeaturesValue = (typeof ParagraphFeatures)[keyof typeof ParagraphFeatures];

/** Runtime values for Adobe Photoshop's `MiddleEasternTextDirection` enum. */
export const MiddleEasternTextDirection = {
  DEFAULT: "dirOverrideDefault",
  LEFTTORIGHT: "dirOverrideLTR",
  RIGHTTOLEFT: "dirOverrideRTL"
} as const;
export type MiddleEasternTextDirectionValue = (typeof MiddleEasternTextDirection)[keyof typeof MiddleEasternTextDirection];

/** Runtime values for Adobe Photoshop's `MiddleEasternDigitsType` enum. */
export const MiddleEasternDigitsType = {
  LTRARABIC: "arabicDigits",
  RTLARABIC: "RTLarabicDigits",
  HINDI: "hindiDigits",
  FARSI: "farsiDigits"
} as const;
export type MiddleEasternDigitsTypeValue = (typeof MiddleEasternDigitsType)[keyof typeof MiddleEasternDigitsType];

/** Runtime values for Adobe Photoshop's `KashidaWidthType` enum. */
export const KashidaWidthType = {
  NONE: "kashidaWidthNone",
  SHORT: "kashidaWidthSmall",
  MEDIUM: "kashidaWidthMedium",
  LONG: "kashidaWidthLong",
  STYLISTIC: "kashidaWidthStylistic"
} as const;
export type KashidaWidthTypeValue = (typeof KashidaWidthType)[keyof typeof KashidaWidthType];

/** Runtime values for Adobe Photoshop's `Kinsoku` enum. */
export const Kinsoku = {
  NONE: "None",
  JISWEAK: "Soft",
  JISMAXIMUM: "Hard"
} as const;
export type KinsokuValue = (typeof Kinsoku)[keyof typeof Kinsoku];

/** Runtime values for Adobe Photoshop's `Mojikumi` enum. */
export const Mojikumi = {
  NONE: "None",
  SET1: "Photoshop6MojiKumiSet1",
  SET2: "Photoshop6MojiKumiSet2",
  SET3: "Photoshop6MojiKumiSet3",
  SET4: "Photoshop6MojiKumiSet4"
} as const;
export type MojikumiValue = (typeof Mojikumi)[keyof typeof Mojikumi];

/** Runtime values for Adobe Photoshop's `GenerativeUpscaleModel` enum. */
export const GenerativeUpscaleModel = {
  FIREFLY: "firefly"
} as const;
export type GenerativeUpscaleModelValue = (typeof GenerativeUpscaleModel)[keyof typeof GenerativeUpscaleModel];

/** Runtime values for Adobe Photoshop's `FlipAxis` enum. */
export const FlipAxis = {
  HORIZONTAL: "horizontal",
  VERTICAL: "vertical",
  BOTH: "both"
} as const;
export type FlipAxisValue = (typeof FlipAxis)[keyof typeof FlipAxis];

/** Every Photoshop constants table, exposed synchronously by the WebView namespace. */
export const PhotoshopConstants = {
  InterpolationMethod,
  ResampleMethod,
  SaveMethod,
  SaveOptions,
  BMPDepthType,
  BitsPerChannelType,
  DepthMapSource,
  OperatingSystem,
  JPEGFormatOptions,
  MatteColor,
  Dither,
  ForcedColors,
  Palette,
  PNGMethod,
  AnchorPosition,
  TrimType,
  LabelColors,
  BlendMode,
  ColorBlendMode,
  CalculationsBlendMode,
  ApplyImageBlendMode,
  DocumentMode,
  NewDocumentMode,
  Units,
  ChangeMode,
  DocumentFill,
  LayerKind,
  ElementPlacement,
  ColorProfileType,
  BitmapConversionType,
  BitmapHalfToneType,
  Intent,
  Direction,
  Orientation,
  ColorModel,
  RasterizeType,
  DialogModes,
  DisplacementMapType,
  ChannelType,
  NoiseDistribution,
  EliminateFields,
  Geometry,
  CreateFields,
  PathKind,
  SelectionType,
  ToolType,
  PointKind,
  ShapeOperation,
  TextureType,
  UndefinedAreas,
  PolarConversionType,
  RadialBlurMethod,
  RadialBlurQuality,
  RippleSize,
  SmartBlurQuality,
  SmartBlurMode,
  SpherizeMode,
  WaveType,
  ZigZagType,
  LensType,
  PreserveShape,
  OffsetUndefinedAreas,
  SampleSize,
  SavePreview,
  ColorPicker,
  EditLogItemsType,
  GridSize,
  GridLineStyle,
  GuideLineStyle,
  MaximizeCompatibility,
  OtherCursors,
  PaintingCursors,
  PointType,
  SaveLogItemsType,
  FontSize,
  TypeUnits,
  RulerUnits,
  TypeInterfaceFeatures,
  CalculationsResult,
  CalculationsChannel,
  ApplyImageChannel,
  CalculationsLayer,
  ApplyImageLayer,
  AntiAlias,
  WarpStyle,
  AutoKernType,
  TextCase,
  Baseline,
  Underline,
  Language,
  Justification,
  StrikeThrough,
  CharacterAlignment,
  ParagraphLayout,
  ParagraphFeatures,
  MiddleEasternTextDirection,
  MiddleEasternDigitsType,
  KashidaWidthType,
  Kinsoku,
  Mojikumi,
  GenerativeUpscaleModel,
  FlipAxis
} as const;

export type PhotoshopConstantsNamespace = typeof PhotoshopConstants;
