export { createPhotoshopNamespace, photoshop } from "./photoshop.js";
export type {
  ActionDescriptor,
  BatchPlayCommandOptions,
  Channels,
  CmykColorView,
  DocumentCloseOptions,
  GrayColorView,
  HsbColorView,
  ImagingBounds,
  LabColorView,
  LayerCreateOptions,
  Layers,
  OpenOptions,
  PhotoshopActions,
  PhotoshopApp,
  PhotoshopNamespace,
  PsChannel,
  PsChannelReadableKey,
  PsChannelWritableProps,
  PsDocument,
  PsDocumentReadableKey,
  PsDocumentWritableProps,
  PsLayer,
  PsLayerReadableKey,
  PsLayerWritableProps,
  PsSolidColor,
  ResizeOptions,
  RgbColorView,
  SolidColorInput
} from "./types.js";
