import { PHOTOSHOP_MODULE_ID, PHOTOSHOP_REMOTE_TYPE } from "@shared/photoshop-api/photoshop-protocol.js";
import type { ShapeOperationValue } from "@shared/photoshop-api/photoshop-constants.js";
import { RemoteClass, type RemoteClassConfig, type RemoteMethodNames, type RemotePropertyDescriptor, type RemoteReference } from "@webview/uxp-api/remote/index.js";
import type { PhotoshopContext } from "./context.js"; import type { PathPoints, PsSubPathItem, PsSubPathItemReadableKey } from "./types.js";
export function createSubPathItemProperties(): Record<string, RemotePropertyDescriptor> { return {
  typename: { writable: false, mutating: false, remoteKey: "typename" }, operation: { writable: false, mutating: false, remoteKey: "operation" }, closed: { writable: false, mutating: false, remoteKey: "closed" },
  parent: { writable: false, mutating: false, remoteKey: "parent", refType: PHOTOSHOP_REMOTE_TYPE.PathItem }, pathPoints: { writable: false, mutating: false, remoteKey: "pathPoints", collectionOf: PHOTOSHOP_REMOTE_TYPE.PathPoint }
}; }
export function createSubPathItemClass(context: PhotoshopContext): { new(reference: RemoteReference): PsSubPathItem } { const properties = createSubPathItemProperties(); const config: RemoteClassConfig = { rpc: context.rpc, moduleId: PHOTOSHOP_MODULE_ID, properties, methods: {}, argEncoders: context.argEncoders, decodeContext: context.registry.decodeContext, methodNames: { propertyGet: Object.fromEntries(Object.keys(properties).map((name) => [name, "subPathItem.propertyGet"])), propertySet: {}, method: {}, batchGet: "subPathItem.batchGet", batchSet: "subPathItem.batchSet", dispose: "subPathItem.dispose" } satisfies RemoteMethodNames };
  class C extends RemoteClass<PsSubPathItem, PsSubPathItemReadableKey, Record<string, never>> implements PsSubPathItem { declare readonly typename: Promise<"SubPathItem">; declare readonly parent: PsSubPathItem["parent"]; declare readonly operation: Promise<ShapeOperationValue>; declare readonly closed: Promise<boolean>; declare readonly pathPoints: Promise<PathPoints>; constructor(reference: RemoteReference) { super(config, reference); } } return C; }
